all: 
	flex main.lex
	bison -g --report=states -y -d main.y
	gcc  lex.yy.c y.tab.c -o main.out
	rm output.j
	./main.out

exec: all
	./main.out

java:
	javac test.java
	javap -c test.class

error: 
	bison --verbose main.y

custom_run:
	./main.out
	java -jar ./jasmin-1.1/jasmin.jar output.j
	java test

jasmine_temp:
	java -jar ./jasmin-1.1/jasmin.jar output.j

run:
	java test

exec_jasm: exec jasmine_temp run
